version: "3.7"

services:
  django:
    image: soohyoen_django:05
    networks:
      - django
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_PASSWORD
    volumes:
      - django_static:/home/djangoProject/staticfiles/
      - django_media:/home/djangoProject/media/
  nginx:
    image: nginx:1.19.5
    networks:
      - django
    volumes:
      - django_static:/data/static/
      - django_media:/data/media/
      - gis_log:/var/log/nginx/
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf

    ports:
      - mode: host
        protocol: tcp
        target: 80
        published: 80

  goaccess:
    image: allinurl/goaccess:1.5.1
    ports:
      - 7890:7890
    volumes:
      - gis_log:/var/log/nginx/
    command: /var/log/nginx/gis_access.log -o /var/log/nginx/report.html --log-format=COMBINED --real-time-html

  mariadb:
    image: mariadb:10.5
    networks:
      - django
    volumes:
      - django_maria:/var/lib/mysql
    secrets:
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD

networks:
  django:

volumes:
  django_static:
  django_media:
  django_maria:
  gis_log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true