# Generated by Django 3.2.6 on 2021-08-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projecct',
            new_name='Project',
        ),
    ]
